## Numpy函数库基础

In [1]:
from numpy import *

In [2]:
random.rand(4,4)

array([[ 0.26541546,  0.8512158 ,  0.68426286,  0.88453909],
       [ 0.18145073,  0.43362737,  0.13405039,  0.82624095],
       [ 0.58039811,  0.07059442,  0.87060385,  0.75069581],
       [ 0.81119219,  0.69267289,  0.34307287,  0.15088346]])

In [4]:
# 矩阵
randMat = mat(random.rand(4,4))
randMat

matrix([[ 0.69670636,  0.56038654,  0.67925546,  0.86039226],
        [ 0.82424191,  0.53307588,  0.99902943,  0.31232612],
        [ 0.22169991,  0.70609153,  0.84373068,  0.38973858],
        [ 0.13790353,  0.54344807,  0.29756483,  0.17534146]])

In [5]:
# 矩阵求逆
invRandMat = randMat.I
invRandMat

matrix([[ 0.27638758,  1.37409714, -2.35088804,  1.42158975],
        [-0.25727216, -0.11083908, -0.81677907,  3.27534195],
        [-0.57957286,  0.33419778,  2.14284364, -2.51433718],
        [ 1.56357625, -1.30432968,  0.74390768, -1.29942   ]])

In [6]:
randMat * invRandMat

matrix([[  1.00000000e+00,   2.22044605e-16,   0.00000000e+00,
          -4.44089210e-16],
        [ -2.77555756e-17,   1.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
           0.00000000e+00],
        [ -2.77555756e-17,   0.00000000e+00,   2.22044605e-16,
           1.00000000e+00]])

In [7]:
myEye = randMat * invRandMat
myEye - eye(4)

matrix([[  0.00000000e+00,   2.22044605e-16,   0.00000000e+00,
          -4.44089210e-16],
        [ -2.77555756e-17,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [ -2.77555756e-17,   0.00000000e+00,   2.22044605e-16,
          -4.44089210e-16]])